repos:
- repo: https://github.com/psf/black
  rev: "22.3.0"
  hooks:
    - id: black-jupyter
- repo: local
  hooks:
    - id: jupyter-nb-clear-output
      name: jupyter-nb-clear-output
      files: \.ipynb$
      stages: [commit]
      language: system
      entry: jupyter nbconvert --clear-output --inplace